CREATE DATABASE IF NOT EXISTS weeber;
USE weeber;

CREATE TABLE IF NOT EXISTS users (
    id          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nickname    VARCHAR(255) CHARACTER SET utf8 NOT NULL,
    email       VARCHAR(255) CHARACTER SET utf8 NOT NULL,
    password    VARCHAR(255) CHARACTER SET utf8 NOT NULL,
    join_date   DATETIME DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDb;

CREATE TABLE IF NOT EXISTS comments (
    id          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id     INT NOT NULL,
    content     TEXT CHARACTER SET utf8 NOT NULL,
    post_date   DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_comments_users FOREIGN KEY (user_id) REFERENCES users (ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDb;

CREATE TABLE IF NOT EXISTS likes (
    id          INT(255) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id     INT(255) NOT NULL,
    comment_id  INT(255) NOT NULL,
    CONSTRAINT fk_likes_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_likes_comments FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT uc_likes UNIQUE (user_id, comment_id)
)ENGINE=InnoDb;

